# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:1234qwer@tcp(127.0.0.1:3306)/fastcc"
        tables:          "sys_userex"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/demo"