// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gocc/internal/app/demo/dao/internal"
)

// internalCcGerenRenwuDao is internal type for wrapping internal DAO implements.
type internalCcGerenRenwuDao = *internal.CcGerenRenwuDao

// ccGerenRenwuDao is the data access object for table cc_geren_renwu.
// You can define custom methods on it to extend its functionality as you wish.
type ccGerenRenwuDao struct {
	internalCcGerenRenwuDao
}

var (
	// CcGerenRenwu is globally public accessible object for table cc_geren_renwu operations.
	CcGerenRenwu = ccGerenRenwuDao{
		internal.NewCcGerenRenwuDao(),
	}
)

// Fill with you ideas below.
