// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gocc/internal/app/demo/dao/internal"
)

// internalCcPingceDao is internal type for wrapping internal DAO implements.
type internalCcPingceDao = *internal.CcPingceDao

// ccPingceDao is the data access object for table cc_pingce.
// You can define custom methods on it to extend its functionality as you wish.
type ccPingceDao struct {
	internalCcPingceDao
}

var (
	// CcPingce is globally public accessible object for table cc_pingce operations.
	CcPingce = ccPingceDao{
		internal.NewCcPingceDao(),
	}
)

// Fill with you ideas below.
