// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gocc/internal/app/demo/dao/internal"
)

// internalCcRoomPhoneDao is internal type for wrapping internal DAO implements.
type internalCcRoomPhoneDao = *internal.CcRoomPhoneDao

// ccRoomPhoneDao is the data access object for table cc_room_phone.
// You can define custom methods on it to extend its functionality as you wish.
type ccRoomPhoneDao struct {
	internalCcRoomPhoneDao
}

var (
	// CcRoomPhone is globally public accessible object for table cc_room_phone operations.
	CcRoomPhone = ccRoomPhoneDao{
		internal.NewCcRoomPhoneDao(),
	}
)

// Fill with you ideas below.
