// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gocc/internal/app/demo/dao/internal"
)

// internalCcZongjieDao is internal type for wrapping internal DAO implements.
type internalCcZongjieDao = *internal.CcZongjieDao

// ccZongjieDao is the data access object for table cc_zongjie.
// You can define custom methods on it to extend its functionality as you wish.
type ccZongjieDao struct {
	internalCcZongjieDao
}

var (
	// CcZongjie is globally public accessible object for table cc_zongjie operations.
	CcZongjie = ccZongjieDao{
		internal.NewCcZongjieDao(),
	}
)

// Fill with you ideas below.
