// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/demo/dao/internal"
)

// internalDemoGenClassDao is internal type for wrapping internal DAO implements.
type internalDemoGenClassDao = *internal.DemoGenClassDao

// demoGenClassDao is the data access object for table demo_gen_class.
// You can define custom methods on it to extend its functionality as you wish.
type demoGenClassDao struct {
	internalDemoGenClassDao
}

var (
	// DemoGenClass is globally public accessible object for table demo_gen_class operations.
	DemoGenClass = demoGenClassDao{
		internal.NewDemoGenClassDao(),
	}
)

// Fill with you ideas below.
