// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/demo/dao/internal"
)

// internalDemoGenDao is internal type for wrapping internal DAO implements.
type internalDemoGenDao = *internal.DemoGenDao

// demoGenDao is the data access object for table demo_gen.
// You can define custom methods on it to extend its functionality as you wish.
type demoGenDao struct {
	internalDemoGenDao
}

var (
	// DemoGen is globally public accessible object for table demo_gen operations.
	DemoGen = demoGenDao{
		internal.NewDemoGenDao(),
	}
)

// Fill with you ideas below.
