// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gocc/internal/app/demo/dao/internal"
)

// internalSysMissionDao is internal type for wrapping internal DAO implements.
type internalSysMissionDao = *internal.SysMissionDao

// sysMissionDao is the data access object for table sys_mission.
// You can define custom methods on it to extend its functionality as you wish.
type sysMissionDao struct {
	internalSysMissionDao
}

var (
	// SysMission is globally public accessible object for table sys_mission operations.
	SysMission = sysMissionDao{
		internal.NewSysMissionDao(),
	}
)

// Fill with you ideas below.
