// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gocc/internal/app/demo/dao/internal"
)

// internalSysUserexDao is internal type for wrapping internal DAO implements.
type internalSysUserexDao = *internal.SysUserexDao

// sysUserexDao is the data access object for table sys_userex.
// You can define custom methods on it to extend its functionality as you wish.
type sysUserexDao struct {
	internalSysUserexDao
}

var (
	// SysUserex is globally public accessible object for table sys_userex operations.
	SysUserex = sysUserexDao{
		internal.NewSysUserexDao(),
	}
)

// Fill with you ideas below.
