// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gocc/internal/app/demo/dao/internal"
)

// internalSysJiangchengDao is internal type for wrapping internal DAO implements.
type internalSysJiangchengDao = *internal.SysJiangchengDao

// sysJiangchengDao is the data access object for table sys_jiangcheng.
// You can define custom methods on it to extend its functionality as you wish.
type sysJiangchengDao struct {
	internalSysJiangchengDao
}

var (
	// SysJiangcheng is globally public accessible object for table sys_jiangcheng operations.
	SysJiangcheng = sysJiangchengDao{
		internal.NewSysJiangchengDao(),
	}
)

// Fill with you ideas below.
